# Generated by Django 4.1.1 on 2022-09-07 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MorOC', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankoffer',
            name='payment',
        ),
    ]
