# Generated by Django 4.1.1 on 2022-09-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MorOC', '0002_remove_bankoffer_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankoffer',
            name='mortgage_rate',
        ),
        migrations.AddField(
            model_name='bankoffer',
            name='max_mortgage_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bankoffer',
            name='min_mortgage_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bankoffer',
            name='price_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bankoffer',
            name='price_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bankoffer',
            name='term_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bankoffer',
            name='term_min',
            field=models.IntegerField(null=True),
        ),
    ]
